change default db server, refactor db migrate code

diff --git a/koha-migrate b/koha-migrate
--- a/koha-migrate
+++ b/koha-migrate
@@ -1,55 +1,167 @@
 #!/bin/bash
+# ------------------------------------------------------------------
+# Author: Lennon Mazonde
+# GitHub: @grandmaestr
+# Title: koha-database-migrate
+# Description: 
+# 	This script migrates your Koha database to another database server.
+# 	You can copy and paste this script onto your server and make it executable by running "chmod a+x /path/to/file_name"
+# 	To run the script, simply go to "/path/to/file_name" or if it's in your home directory, run "~/file_name" in the CLI.
+# 	This script is interactive, so you'll be prompted for input at various stages.
+# 	You can modify or use this script however you like but I'd really appreciate it if you give me a shout out or attribution if you post it elsewhere :)
 
-# This script migrates your local koha databases to a remote database server.
+# ------------------------------------------------------------------
+set -x 
+set -e
 
-echo "You have the following Koha instances running on this server:"
-echo $(koha-list)
-printf "\n"
+# Script version
+VERSION=0.1.0
+# Set the name of the script to variable
+SCRIPT_NAME="$(basename ${0})"
 
-# Prompt the user for the name(s) of the Koha instance(s) they want to migrate 
-read -p "Enter the name of each  Koha instance database you want to migrate separated by a space:	" -a instance
+# ------Help--------------------------------------------------------
+Help(){
+    # Display Help
+    cat <<EOF
+        Usage: $SCRIPT_NAME [options] 
 
-# Prompt the user for the remote database endpoint
-read -p "Enter the URL/endpoint of your database server:   " hostname
+        Options:
+		d - The hostname, IP address or URL of the destination database.
+		c - The IP or URL address of the client (running the Koha web server). If using a VPC in AWS, Azure, or GCP enter the **Private** IP of your EC2 instance. Defaults to localhost. 
+ 		h - help. Print this help.
+		i - InstanceId. The name of the Koha instance.
+		v - version. Print the script version.
+
+        Example:
+            $SCRIPT_NAME -i library -d mydb.123456789012.us-east-1.rds.amazonaws.com -c 172.16.78.121 
+EOF
+}
+
+# --- Options processing -------------------------------------------
+if [ $# == 0 ] ; then
+    Help
+    exit 1;
+fi
+
+while getopts ":d:c:h:i:v" optname; do
+    case "$optname" in
+		d) 
+			hostname=("$OPTARG")
+			;;
+		c) 
+			clientipaddr=("$OPTARG")
+			;;
+		h)
+			Help
+			exit 0;
+			;;
+		i) 
+			instanceid=("$OPTARG")
+			;;
+		v)
+			echo "Version $VERSION"
+			exit 0;
+			;;
+		\?)
+			echo "Unknown option $OPTARG"
+			Help
+			exit 0;
+			;;
+		:)
+			echo "Error: you must provide an argument for option -$OPTARG"
+			exit 0;
+			;;
+		*)
+			echo "Unknown error while processing options"
+			Help
+			exit 0;
+			;;
+    esac
+  done
+
+shift $(($OPTIND - 1))
+
+param1=$1
+param2=$2
+
+# --- Install remote db --------------------------------------------
+MigrateDB(){
+    # Set the path to koha_conf.xml
+    koha_conf=/etc/koha/sites/$val/koha-conf.xml
+
+    # Retrieve the Koha user, password
+    kohadbpwd=$(sudo xmlstarlet sel -t -v 'yazgfs/config/pass' $koha_conf)
+    kohadbuser=$(sudo xmlstarlet sel -t -v 'yazgfs/config/hostname' $koha_conf)
+
+    # Dump Koha database from the source db server
+    mysqldump -u${kohadbuser} -p${kohadbpwd} --single-transaction --databases koha_$val  > /tmp/koha_$val.sql
+
+    # Restore Koha database to destination db server
+    mysql -h ${hostname} -u ${remotedbroot} -p${remotedbpwd} < /tmp/koha_$val.sql
+
+    koha-rebuild-zebra --full "$val"
+}
+# --- Install remote db --------------------------------------------
+CreateRemoteKohaUserMySQL(){
+	# Create Koha user in remote db server
+    mysql -h ${hostname} -u ${remotedbroot} -p${remotedbpwd} -e "
+    CREATE USER IF NOT EXISTS 'koha_$val'@'${clientipaddr}' IDENTIFIED BY '${kohadbpwd}';
+    GRANT ALL PRIVILEGES ON koha_$val.* to 'koha_$val'@'${clientipaddr}';
+    FLUSH PRIVILEGES;"
+}
+# --- Install remote db aurora--------------------------------------
+CreateRemoteKohaUserAurora(){
+    mysql -h ${hostname} -u ${remotedbroot} -p${remotedbpwd} -e "
+	CREATE USER 'koha_${val}'@'${clientipaddr}' IDENTIFIED B}';
+	GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER, CREATE TEMPORARY TABLES,
+	CREATE VIEW, EVENT, TRIGGER, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, EXECUTE ON koha_${val}.* to 'koha_${val}'@'${clientipaddr}'; FLUSH PRIVILEGES;"
+}	
+# --- Create koha-common.cnf --------------------------------------
+CreateKohaCommon(){
+	echo "
+	[client]
+	host     = ${hostname}
+	user     = ${remotedbroot}
+	password = ${remotedbpass}
+	socket   = /var/run/mysqld/mysqld.sock
+	[mysql_upgrade]
+	host     = ${hostname}
+	user     = ${remotedbroot}
+	password = ${remotedbpass}
+	socket   = /var/run/mysqld/mysqld.sock
+	" | sudo tee /etc/mysql/koha-common.cnf >/dev/null 
+}
+# --- Locks -------------------------------------------------------
+LOCK_FILE=/tmp/$SCRIPT_NAME.lock
+if [ -f "$LOCK_FILE" ]; then
+   echo "Script is already running"
+   exit
+fi
+
+trap "rm -f $LOCK_FILE" EXIT
+touch $LOCK_FILE
+
+# --- Body --------------------------------------------------------
 
 # Prompt user for root user of the remote database server
-read -p "Enter the username of your remote database root user:	" remotedbroot
+echo "Enter the root user of the destination server:	" 
+read -s remotedbroot
 
 # Prompt user for password of the remote database server
-read -p  "Enter the password for the root user of your remote database server:	" remotedbpwd
-
-# Prompt user for root user of the local database server
-read -p "Enter the username of your local database root user:  " localdbroot
-
-# Prompt user for local db server password
-read -p  "Enter the password for the root user of your local database server:	" localdbpwd
-
-# Prompt user for IP address of client server. If using AWS EC2 instances, enter the private IP
-read -p "Enter the IP address of your client server (i.e. the server runnning the Koha web application):   " clientipaddr
+echo  "Enter the password for destination server root user:	" 
+read -s remotedbpwd
 
 # Enable and start  Koha instances
-for instancename in "${instance[@]}"; do
+for val in "${instance[@]}"; do
 
-# Set the path to koha_conf.xml
-koha_conf=/etc/koha/sites/$instancename/koha-conf.xml
-
-# Retrieve the Koha user password in koha-conf.xml
-remotekohadbpwd=$(sudo xmlstarlet sel -t -v 'yazgfs/config/pass' $koha_conf)
-
-# Dump Koha database
-mysqldump -u${localdbroot} -p${localdbpwd} --single-transaction --databases koha_$instancename  --set-gtid-purged=OFF > /tmp/koha_$instancename.sql
-
-# Restore Koha database to remote db server
-mysql -h ${hostname} -u ${remotedbroot} -p${remotedbpwd} < /tmp/koha_$instancename.sql
+# Dump and migrate Koha instance database from source to destination db server
+MigrateDB
 
 # Create Koha user in remote db server
-mysql -h ${hostname} -u ${remotedbroot} -p${remotedbpwd} -e "
-CREATE USER IF NOT EXISTS 'koha_${instancename}'@'${clientipaddr}' IDENTIFIED BY '${remotekohadbpwd}';
-GRANT ALL PRIVILEGES ON koha_${instancename}.* to 'koha_${instancename}'@'${clientipaddr}';
-FLUSH PRIVILEGES;"
+CreateRemoteKohaUserMySQL
 
 # Delete database dump in /tmp/
-sudo rm -f /tmp/koha_$instancename.sql
+sudo rm -f /tmp/koha_$val.sql
 
 # Replace database endpoint with remote db endpoint
 sudo xmlstarlet edit -L --update 'yazgfs/config/hostname' --value "$hostname" $koha_conf
@@ -57,20 +169,9 @@ sudo xmlstarlet edit -L --update 'yazgfs/config/hostname' --value "$hostname" $k
 done
 
 # Update koha-common.cnf with config for remote db
-echo "
-[client]
-host     = ${hostname}
-user     = ${remotedbroot}
-password = ${remotedbpwd}
-socket   = /var/run/mysqld/mysqld.sock
-[mysql_upgrade]
-host     = ${hostname}
-user     = ${remotedbroot}
-password = ${remotedbpwd}
-socket   = /var/run/mysqld/mysqld.sock
-" | sudo tee /etc/mysql/koha-common.cnf >/dev/null
+CreateKohaCommon
 
 # Reload koha-common and memcached
 sudo systemctl restart koha-common.service memcached.service
 
-echo "Success"
+echo "Done"
