fix s3 block

diff --git a/koha-backup-s3 b/koha-backup-s3
--- a/koha-backup-s3
+++ b/koha-backup-s3
@@ -109,14 +109,14 @@ else
     # Make the dump files readable and writeable by the current user.
     sudo chown $(whoami):$(whoami) "$dbdump" "$metadump"
 
-    if [ -n "$s3_url" ]; then
-        [ "$quiet" = "no" ] && echo "* copying backups to S3 bucket: $s3_url"
-        aws s3 cp "$dbdump" "$s3_url/$name/$name-$date.sql.gz"
-        aws s3 cp "$metadump" "$s3_url/$name/$name-$date.tar.gz"
-     else
-        echo "Error: S3 URL is empty. Please provide a valid S3 URL."
-        usage
-        exit 1
+        if [ "$s3_url" -eq 0 ]; then
+            echo "Error: S3 URL is empty. Please provide a valid S3 URL." >&2
+            usage
+            exit 1
+        else
+            [ "$quiet" = "no" ] && echo "* copying backups to S3 bucket: $s3_url"
+            aws s3 cp "$dbdump" "$s3_url/$name/$name-$date.sql.gz"
+            aws s3 cp "$metadump" "$s3_url/$name/$name-$date.tar.gz"
     fi
 
     [ "$quiet" = "no" ] && echo "Done."
