refactor with functions

diff --git a/koha-borrower_relationships_table_error_fix b/koha-borrower_relationships_table_error_fix
--- a/koha-borrower_relationships_table_error_fix
+++ b/koha-borrower_relationships_table_error_fix
@@ -22,162 +22,165 @@
 # THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 # ------------------------------------------------------------------
 
-# Script version
-VERSION=0.1.0
-# Set the name of the script to variable
-SCRIPT_NAME="$(basename ${0})"
-SUBJECT=koha-borrower_relationships_table_error_fix
+# Script configuration
+VERSION="0.1.0"
+SUBJECT="koha-borrower_relationships_table_error_fix"
+SCRIPT_NAME="$(basename "${0}")"
+LOCK_FILE="/tmp/${SUBJECT}.lock"
+REQUIRED_TOOLS=("sudo" "koha-run-backups" "koha-worker" "koha-plack" "koha-zebra" "koha-remove" "deluser" "systemctl" "koha-restore" "koha-mysql" "koha-upgrade-schema")
 
-# ------Help--------------------------------------------------------
-Help(){
-    # Display Help
-    cat <<EOF
-        Usage: $SCRIPT_NAME -ihv args
+# Functions
+function help_message() {
+  cat <<EOF
+Usage: ${SCRIPT_NAME} -i <instance_id> [-h] [-v]
 
-        Options:
-        i - instanceid. The name of the koha instance. One instance id per option.
-        h - help. Print this help.
-        v - version. Print the script version.
+Options:
+  -i: The name of the koha instance. Can be specified multiple times.
+  -h: Print help message.
+  -v: Print version.
 
-        Example:
-        To run the script on a single instance called "library", run:
-            $SCRIPT_NAME -i library
-        For multiple instances, run
-                $SCRIPT_NAME -i library1 -i library2 ...
+Examples:
+  ${SCRIPT_NAME} -i library
+  ${SCRIPT_NAME} -i library1 -i library2
 EOF
 }
-# --- Options processing -------------------------------------------
-if [ $# == 0 ] ; then
-    Help
-    exit 1;
-fi
 
-while getopts ":i:vh" optname; do
-    case "$optname" in
-      v)
-        echo "Version $VERSION"
-        exit 0;
+function check_requirements() {
+  for tool in "${REQUIRED_TOOLS[@]}"; do
+    if ! command -v "${tool}" >/dev/null 2>&1; then
+      echo "Error: ${tool} is not installed or is not in the system path." >&2
+      exit 1
+    fi
+  done
+}
+
+function backup_instance() {
+  local instance_id="$1"
+  echo "Running backup for ${instance_id}. Please be patient."
+  sudo koha-run-backups "${instance_id}" >/dev/null 2>&1
+  echo "Backup for ${instance_id} complete."
+}
+
+function restore_instance() {
+  local instance_id="$1"
+  sudo koha-worker --stop "${instance_id}"
+  sudo koha-plack --stop "${instance_id}"
+  sudo koha-zebra --stop "${instance_id}"
+  sudo koha-remove "${instance_id}"
+  sudo deluser "${instance_id}-koha"
+  sudo rm -f "/etc/apache2/sites-enabled/${instance_id}.conf" "/etc/apache2/sites-enabled/${instance_id}-le-ssl.conf"
+  sudo rm -rf "/etc/koha/sites/${instance_id}"
+  sudo rm -rf "/var/lib/koha/${instance_id}"
+  sudo systemctl restart apache2.service "${instance_id}"
+
+  # Set path to backup files
+  sqldump=$(sudo ls "/var/spool/koha/${instance_id}"/*.sql.gz -t | head -n1)
+  configdump=$(sudo ls "/var/spool/koha/${instance_id}"/*.tar.gz -t | head -n1)
+  sudo koha-restore "${sqldump}" "${configdump}"
+  sudo koha-worker --start "${instance_id}"
+  sudo koha-plack --enable "${instance_id}"
+  sudo koha-plack --start "${instance_id}"
+  sudo koha-zebra --start "${instance_id}"
+}
+
+function drop_foreign_key() {
+  local instance_id="$1"
+  while true; do
+    read -rp "Drop and recreate the foreign key 'r_guarantor' for ${instance_id}? " response
+    case "${response}" in
+      [yY][eE][sS]|[yY])
+        # Backup database
+        while true; do
+          read -rp "Backup all your Koha instances? This step is strongly recommended. " response
+          case "${response}" in
+            [yY][eE][sS]|[yY])
+              backup_instance "${instance_id}"
+              break
+              ;;
+            [nN][oO]|[nN])
+              echo "Skipping backup"
+              ;;
+            [qQ][uU][iI][tT]|[qQ])
+              exit
+              ;;
+            *)
+              echo "Invalid response. Try again."
+              ;;
+          esac
+        done
+
+        # Drop the foreign key
+        sudo koha-mysql "${instance_id}" -Nse "ALTER TABLE borrower_relationships DROP FOREIGN KEY r_guarantor; ALTER TABLE borrower_relationships MODIFY COLUMN guarantor_id INT(11) COLLATE utf8mb4_unicode_ci NOT NULL;"
+
+        # Upgrade the database schema
+        sudo koha-upgrade-schema "${instance_id}"
+
+        # Add the foreign key
+        sudo koha-mysql "${instance_id}" -Nse "ALTER TABLE borrower_relationships ADD CONSTRAINT r_guarantor FOREIGN KEY (guarantor_id) REFERENCES borrowers (borrowernumber) ON DELETE CASCADE ON UPDATE CASCADE;"
+        echo "The foreign key drop and recreate operation for ${instance_id} is complete. If the koha-upgrade-schema command above produces errors, you will need to resolve those errors before you can successfully complete the upgrade process."
+        sleep 1s
+        break
         ;;
-      i)  
-        instanceid+=("$OPTARG")
+      [nN][oO]|[nN])
+        echo "No changes have been made."
+        break
         ;;
-      h)
-        Help
-        exit 0;
-        ;;
-      \?)
-        echo "Unknown option $OPTARG"
-        Help
-        exit 0;
-        ;;
-      :)
-        echo "Error: you must provide at least one instance name for option -$OPTARG"
-        exit 0;
+      [qQ][uU][iI][tT]|[qQ])
+        exit
         ;;
       *)
-        echo "Unknown error while processing options"
-        Help
-        exit 0;
+        echo "Invalid response. Try again."
         ;;
     esac
   done
-
-shift $(($OPTIND - 1))
-
-param1=$1
-param2=$2
-
-# --- Backup Original Config -------------------------------------
-Backup(){
-	# Backup 
-        sudo koha-run-backups
-}
-# --- Restore Original Config -------------------------------------
-Restore(){
-	# Stop and remove Koha instance
-        sudo koha-worker --stop $val
-        sudo koha-plack --stop $val
-        sudo koha-zebra --stop $val
-        sudo koha-remove $val
-        sudo deluser ${val}-koha
-        sudo rm /etc/apache2/sites-enabled/$val.conf /etc/apache2/sites-enabled/$val-le-ssl.conf 
-        sudo rm -rf /etc/koha/sites/$val
-        sudo rm -rf /var/lib/koha/$val
-        sudo systemctl restart apache2.service $val
-
-        # Set path to backup files
-        sqldump=$(sudo ls /var/spool/koha/$val/*.sql.gz -t | head -n1)
-        configdump=$(sudo ls /var/spool/koha/$val/*.tar.gz -t | head -n1)
-        sudo koha-restore $sqldump $configdump
-        sudo koha-worker --start $val
-        sudo koha-plack --enable $val
-        sudo koha-plack --start $val
-        sudo koha-zebra --start $val
 }
 
-# --- Locks -------------------------------------------------------
-LOCK_FILE=/tmp/$SUBJECT.lock
-if [ -f "$LOCK_FILE" ]; then
-   echo "Script is already running"
-   exit
+# Check requirements
+check_requirements
+
+# Parse command-line options
+instance_ids=()
+while getopts "hi:v" option; do
+  case "${option}" in
+    i)
+      instance_ids+=("${OPTARG}")
+      ;;
+    v)
+      echo "Version ${VERSION}"
+      exit 0
+      ;;
+    h)
+      help_message
+      exit 0
+      ;;
+    *)
+      echo "Invalid option: -${OPTARG}" >&2
+      help_message >&2
+      exit 1
+      ;;
+  esac
+done
+shift $((OPTIND - 1))
+
+# Check that instance_ids is not empty
+if [[ ${#instance_ids[@]} -eq 0 ]]; then
+  echo "Error: you must specify at least one instance id." >&2
+  help_message >&2
+  exit 1
 fi
 
-trap "rm -f $LOCK_FILE" EXIT
-touch $LOCK_FILE
+# Ensure that only one instance is being operated on at a time
+if [[ -f "${LOCK_FILE}" ]]; then
+  echo "Error: ${SCRIPT_NAME} is already running." >&2
+  exit 1
+fi
+trap "rm -f ${LOCK_FILE}" EXIT
+touch "${LOCK_FILE}"
 
-# --- Body --------------------------------------------------------
-set -x
-
-
-time=$(date +"%d_%m_%Y_%T")
-# Enable and start  Koha instances
-for val in "${instanceid[@]}"; do 
-	while true; do
-		read -p "Drop and recreate the foreign key 'r_guarantor' for $val?:  " response 
-
-		case $response in
-                [yY][eE][sS]|[yY] )
-                        # Backup database
-                                while true; do
-                                      read -p "Backup all your Koha instances? This step is strongly recommended." response 
-                                         case $response in
-                                                 [yY][eE][sS]|[yY] )
-                                                        printf "Running backup. Please be patient. \n";
-                                                        Backup 2>/dev/null;
-                                                        printf "Backup complete \n";
-                                                break;;
-                                        
-                                                [nN][oO]|[nN] ) 
-                                                        printf "Skipping backup. \n";
-                                                break;;
-
-                                        [qQ][uU][iI][tT] | [qQ] )
-                                                exit;;
-
-                                        * ) echo Invalid response.Try again;;
-                                        esac
-                                done
-
-                        # Drop the foreign key
-                        echo print
-                        sudo koha-mysql $val -Nse "ALTER TABLE borrower_relationships DROP FOREIGN KEY r_guarantor;ALTER TABLE borrower_relationships MODIFY COLUMN guarantor_id INT(11) COLLATE utf8mb4_unicode_ci NOT NULL;"
-
-                        # Upgrade the database schema
-                        sudo koha-upgrade-schema $val 
-                        
-                        # Add the foreign key
-                        sudo koha-mysql $val -Nse "ALTER TABLE borrower_relationships ADD CONSTRAINT r_guarantor FOREIGN KEY (guarantor_id) REFERENCES borrowers (borrowernumber) ON DELETE CASCADE ON UPDATE CASCADE;"
-                        printf "The foreign key drop and recreate operation for $val is complete. \n If the koha-upgrade-schema commmand above produces errors, you will need to resolve those errors before you can successfully complete the upgrade process. \n"
-                        sleep 1s
-			break;;
-
-                [nN][oO]|[nN] ) echo No changes have been made;
-                        break;;
-
-                [qQ][uU][iI][tT] | [qQ] )
-                        exit;;
-
-                * ) echo Invalid response.Try again;;
-                esac
-        done
+# Perform operations on each instance id
+for instance_id in "${instance_ids[@]}"; do
+  drop_foreign_key "${instance_id}"
 done
+
+exit 0
+
