fix syntax error

diff --git a/koha-backup-s3 b/koha-backup-s3
--- a/koha-backup-s3
+++ b/koha-backup-s3
@@ -81,128 +81,117 @@ dump_instance() {
     dbflag="--databases"
     [ "$without_db_name" = "yes" ] && dbflag=""
     if [ "$schema_only" = "yes" ]; then
-        schemadump="$backupdir    /$name-schema-$date.sql"
-    [ "$quiet" = "no" ] && echo "* schema to $schemadump"
-    mysqldump $dbflag --no-tablespaces -d --host="$mysqlhost" --single-transaction --user="$mysqluser" --password="$mysqlpass" "$mysqldb" | sed --expression='s/ AUTO_INCREMENT=[0-9]\+//' > "$schemadump"
+        schemadump="$backupdir/$name-schema-$date.sql"
+        [ "$quiet" = "no" ] && echo "* schema to $schemadump"
+        mysqldump $dbflag --no-tablespaces -d --host="$mysqlhost" --single-transaction --user="$mysqluser" --password="$mysqlpass" "$mysqldb" | sed --expression='s/ AUTO_INCREMENT=[0-9]\+//' > "$schemadump"
+    else
+        [ "$quiet" = "no" ] && echo "* DB to $dbdump"
+        mysqldump $dbflag --no-tablespaces --host="$mysqlhost" --single-transaction --user="$mysqluser" --password="$mysqlpass" "$mysqldb" | gzip > "$dbdump"
 
-else
-    [ "$quiet" = "no" ] && echo "* DB to $dbdump"
-    mysqldump $dbflag --no-tablespaces --host="$mysqlhost" --single-transaction --user="$mysqluser" --password="$mysqlpass" "$mysqldb" | gzip > "$dbdump"
+        instancefile="$name.conf"
 
-    instancefile="$name.conf"
+        # Dump configs, logs, etc.
+        metadump="$backupdir/$name-$date.tar.gz"
+        [ "$quiet" = "no" ] && echo "* configs, logs to $metadump"
 
-    # Dump configs, logs, etc.
-    metadump="$backupdir/$name-$date.tar.gz"
-    [ "$quiet" = "no" ] && echo "* configs, logs to $metadump"
+        if [ "$exclude_indexes" = "yes" ]; then
+            excludes="--exclude=var/lib/koha/$name/biblios \
+                      --exclude=var/lib/koha/$name/authorities"
+        fi
 
-    if [ "$exclude_indexes" = "yes" ]; then
-        excludes="--exclude=var/lib/koha/$name/biblios \
-                  --exclude=var/lib/koha/$name/authorities"
+        sudo tar -czf "$metadump" -C / $excludes \
+            "etc/koha/sites/$name" \
+            "etc/apache2/sites-available/$instancefile" \
+            "etc/apache2/sites-enabled/$instancefile" \
+            "var/lib/koha/$name" \
+            "var/log/koha/$name"
+
+        # Make the dump files readable and writeable by the current user.
+        sudo chown $(whoami):$(whoami) "$dbdump" "$metadump"
+
+        if [ -n "$s3_url" ]; then
+            [ "$quiet" = "no" ] && echo "* copying backups to S3 bucket: $s3_url"
+            aws s3 cp "$dbdump" "$s3_url/$name/$name-$date.sql.gz"
+            aws s3 cp "$metadump" "$s3_url/$name/$name-$date.tar.gz"
+        fi
+
+        [ "$quiet" = "no" ] && echo "Done."
     fi
-
-    sudo tar -czf "$metadump" -C / $excludes \
-        "etc/koha/sites/$name" \
-        "etc/apache2/sites-available/$instancefile" \
-        "etc/apache2/sites-enabled/$instancefile" \
-        "var/lib/koha/$name" \
-        "var/log/koha/$name"
-
-    # Make the dump files readable and writeable by the current user.
-    sudo chown $(whoami):$(whoami) "$dbdump" "$metadump"
-
-    if [ -n "$s3_url" ]; then
-       
-    /$name-schema-$date.sql"
-    [ "$quiet" = "no" ] && echo "* schema to $schemadump"
-    mysqldump $dbflag --no-tablespaces -d --host="$mysqlhost" --single-transaction --user="$mysqluser" --password="$mysqlpass" "$mysqldb" | sed --expression='s/ AUTO_INCREMENT=[0-9]\+//' > "$schemadump"
-
-else
-    [ "$quiet" = "no" ] && echo "* DB to $dbdump"
-    mysqldump $dbflag --no-tablespaces --host="$mysqlhost" --single-transaction --user="$mysqluser" --password="$mysqlpass" "$mysqldb" | gzip > "$dbdump"
-
-    instancefile="$name.conf"
-
-    # Dump configs, logs, etc.
-    metadump="$backupdir/$name-$date.tar.gz"
-    [ "$quiet" = "no" ] && echo "* configs, logs to $metadump"
-
-    if [ "$exclude_indexes" = "yes" ]; then
-        excludes="--exclude=var/lib/koha/$name/biblios \
-                  --exclude=var/lib/koha/$name/authorities"
-    fi
-
-    sudo tar -czf "$metadump" -C / $excludes \
-        "etc/koha/sites/$name" \
-        "etc/apache2/sites-available/$instancefile" \
-        "etc/apache2/sites-enabled/$instancefile" \
-        "var/lib/koha/$name" \
-        "var/log/koha/$name"
-
-    # Make the dump files readable and writeable by the current user.
-    sudo chown $(whoami):$(whoami) "$dbdump" "$metadump"
-
-    if [ -n "$s3_url" ]; then
-        [ "$quiet" = "no" ] && echo "* copying backups to S3 bucket: $s3_url"
-        aws s3 cp "$dbdump" "$s3_url/$name/$name-$date.sql.gz"
-        aws s3 cp "$metadump" "$s3_url/$name/$name-$date.tar.gz"
-    fi
-
-    [ "$quiet" = "no" ] && echo "Done."
-fi
 }
 
 while [ $# -gt 0 ]; do
-case "$1" in
---schema-only)
-schema_only="yes"
-shift ;;
---exclude-indexes)
-exclude_indexes="yes"
-shift ;;
---without-db-name)
-without_db_name="yes"
-shift ;;
--i)
-shift
-while [ $# -gt 0 ] && ! [[ "$1" =~ ^- ]]; do
-instances+=("$1")
-shift
-done ;;
--s)
-shift
-s3_url="$1"
-shift ;;
--h|--help)
-usage ; exit 0 ;;
--q|--quiet)
-quiet="yes"
-shift ;;
--*)
-echo "Error: invalid option switch ("$1")" >&2; usage; exit 1 ;;
-*)
-# We expect the remaining stuff are the instance names
-break ;;
-esac
+    case "$1" in
+        --schema-only)
+            schema_only="yes"
+            shift ;;
+        --exclude-indexes)
+            exclude_indexes="yes"
+            shift ;;
+        --without-db-name)
+            without_db_name="yes"
+            shift ;;
+        -i)
+            shift
+            while [ $# -gt 0 ] && ! [[ "$1" =~ ^- ]]; do
+                instances+=("$1")
+                shift
+            done ;;
+        -s)
+            shift
+            s3_url="$1"
+            shift ;;
+        -h|--help)
+            usage ; exit 0 ;;
+        -q|--quiet)
+            quiet="yes"
+            shift ;;
+        -*)
+            echo "Error: invalid option switch ("$1")" >&2; usage; exit 1 ;;
+        *)
+            # We expect the remaining stuff are the instance names
+            break ;;
+    esac
 done
 
 # Read instance names
 if [ "${#instances[@]}" -gt 0 ]; then
-# We have at least one instance name
-for name in "${instances[@]}"; do
-if is_instance "$name"; then
-dump_instance "$name"
+    # We have at least one instance name
+    for name in "${instances[@]}"; do
+        if is_instance "$name"; then
+            dump_instance "$name"
+        else
+            if [ "$quiet" = "no" ]; then
+                echo "Error: Invalid instance name $name" >&2
+            fi
+            exit 1
+        fi
+    done
 else
-if [ "$quiet" = "no" ]; then
-echo "Error: Invalid instance name $name" >&2
+    if [ "$quiet" = "no" ]; then
+        echo "Error: you must provide at least one instance name" >&2
+    fi
+    usage; exit 1
 fi
-exit 1
-fi
-done
+
+exit 0
+
+if [ "${#instances[@]}" -gt 0 ]; then
+    # We have at least one instance name
+    for name in "${instances[@]}"; do
+        if is_instance "$name"; then
+            dump_instance "$name"
+        else
+            if [ "$quiet" = "no" ]; then
+                echo "Error: Invalid instance name $name" >&2
+            fi
+            exit 1
+        fi
+    done
 else
-if [ "$quiet" = "no" ]; then
-echo "Error: you must provide at least one instance name" >&2
-fi
-usage; exit 1
+    if [ "$quiet" = "no" ]; then
+        echo "Error: you must provide at least one instance name" >&2
+    fi
+    usage; exit 1
 fi
 
 exit 0
