add time out to tail command

diff --git a/koha-dbms-autoincrement-fix b/koha-dbms-autoincrement-fix
--- a/koha-dbms-autoincrement-fix
+++ b/koha-dbms-autoincrement-fix
@@ -25,7 +25,7 @@
 # OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 # THE SOFTWARE.
 
-set -euox pipefail  # Enable error checking and strict mode
+set -euo pipefail  # Enable error checking and strict mode
 IFS=$'\n\t'
 
 echo -e "\e[33mWarning: This script will make changes to your system.\e[0m"
@@ -53,8 +53,12 @@ if [[ "$confirmation" == [yY] || "$confirmation" == [yY][eE][sS] ]]; then
     # Restart mysql service to execute the init script
     sudo systemctl restart mysql
 
-    # Confirm that the koha-mysql-init service ran successfully by searching for the string 'koha' in /var/log/syslog
-    sudo tail -f /var/log/syslog | grep -i koha
-else
+    echo -e "\e[32mKoha autoincrement fix completed successfully.\e[0m"
+    echo -e "\e[33mPlease check the system logs if there were any errors or warnings during the script execution.\e[0m"
+
+    # Monitor the system log file for new lines containing 'koha' for up to 5 seconds
+    
+    timeout 5s sudo tail -f /var/log/syslog | grep -i koha || true
+     else
     echo "Aborted by user."
-fi
+    fi
