fix backup file issue

diff --git a/koha-insert-encryption-key b/koha-insert-encryption-key
--- a/koha-insert-encryption-key
+++ b/koha-insert-encryption-key
@@ -71,41 +71,31 @@ while getopts ":i:vh" optname; do
       exit 1;
       ;;
     :)
-      echo -e "${RED}Error: you must provide at least one instance name for option -$OPTARG${NC}"
-      Help
-      exit 1;
-      ;;
-    *)
-      echo -e "${RED}Unknown error while processing options${NC}"
-      Help
-      exit 1;
-      ;;
-  esac
+      echo -e "${RED}Error: you must provide at least one instance name for option -$
+OPTARG${NC}"
+Help
+exit 1;
+;;
+*)
+echo -e "${RED}Unknown error while processing options${NC}"
+Help
+exit 1;
+;;
+esac
 done
 
 # Check if instanceid array is empty
 if [ ${#instanceid[@]} -eq 0 ]; then
-  echo -e "${RED}Error: you must provide at least one instance name${NC}"
-  Help
-  exit 1
+echo -e "${RED}Error: you must provide at least one instance name${NC}"
+Help
+exit 1
 fi
-
-# Backup Original Config
-Backup() {
-  config_backup="/tmp/$val.koha-conf.xml.bkp-$(date +%d-%m-%Y-%Hh%Mm%Ss)"
-  sudo cp "$configpath" "$config_backup"
-}
-
-# Restore Original Config
-Restore() {
-  sudo cp "$config_backup" "$configpath"
-}
 
 # Locks
 LOCK_FILE="/tmp/$SUBJECT.lock"
 if [ -f "$LOCK_FILE" ]; then
-  echo -e "${RED}Script is already running${NC}"
-  exit 1
+echo -e "${RED}Script is already running${NC}"
+exit 1
 fi
 
 trap "rm -f $LOCK_FILE" EXIT
@@ -116,65 +106,84 @@ configpath=""
 
 # Body
 for val in "${instanceid[@]}"; do
-  CheckConfigFile "$val"
+CheckConfigFile "$val"
 
-  # Set path to koha-conf.xml
-  configpath="/etc/koha/sites/$val/koha-conf.xml"
+# Set path to koha-conf.xml
+configpath="/etc/koha/sites/$val/koha-conf.xml"
 
-  # Check if encryption key element exists
-	if [ "$(sudo xmlstarlet sel -t -v "count(yazgfs/config/encryption_key)" "$configpath")" -eq "0" ]; then
-		echo -e "${YELLOW}Encryption key not found. Adding new encryption key...${NC}"
-		sleep 1s
-		# Backup the original config file
-		Backup
+# Check if encryption key element exists
+if [ "$(sudo xmlstarlet sel -t -v "count(yazgfs/config/encryption_key)" "$configpath")" -eq "0" ]; then
+echo -e "${YELLOW}Encryption key not found. Adding new encryption key...${NC}"
+sleep 1s
 
-		# Generate encryption key and set to variable
-		keyvalue=$(pwgen 32 -1)
+# Generate encryption key and set to variable
+keyvalue=$(pwgen 32 -1)
 
-		# Insert new encryption key element
-		sudo xmlstarlet ed -L -P -s "/yazgfs/config" -t elem -n encryption_key -v "$keyvalue" "$configpath"
+# Backup the original config file
+local config_backup="/tmp/$val.koha-conf.xml.bkp-$(date +%d-%m-%Y-%Hh%Mm%Ss)"
+sudo cp "$configpath" "$config_backup"
 
-		# Prompt to restore original config
-		echo -e "${GREEN}The koha-conf.xml file for $val has been updated.${NC}"
-		read -rp "Do you want to restore the original file? (yes/no): " response
-		case $response in
-		[yY][eE][sS]|[yY])
-			Restore
-			echo -e "${GREEN}The original config has been restored.${NC}"
-			;;
-		[nN][oO]|[nN])
-			echo -e "${GREEN}Changes kept.${NC}"
-			;;
-		*)
-			echo -e "${RED}Invalid response.${NC}"
-			;;
-		esac
-		else
-			echo -e "${YELLOW}Encryption key exists.${NC}"
-			read -rp "Do you want to update it? (yes/no): " response
-			case $response in
-			[yY][eE][sS]|[yY])
-			echo -e "${YELLOW}Updating encryption key...${NC}"
-			sleep 1s
-			
-			# Backup the original config file
-			Backup
+# Insert new encryption key element
+sudo xmlstarlet ed -L -P -s "/yazgfs/config" -t elem -n encryption_key -v "$keyvalue" "$configpath"
 
-			# Generate encryption key and set to variable
-			keyvalue=$(pwgen 32 -1)
+# Prompt to restore original config
+echo -e "${GREEN}The koha-conf.xml file for $val has been updated.${NC}"
+read -rp "Do you want to restore the original file? (yes/no): " response
+case $response in
+[yY][eE][sS]|[yY])
+  sudo cp "$config_backup" "$configpath"
+  echo -e "${GREEN}The original config has been restored.${NC}"
+  ;;
+[nN][oO]|[nN])
+  echo -e "${GREEN}Changes kept.${NC}"
+  ;;
+*)
+  echo -e "${RED}Invalid response.${NC}"
+  ;;
+esac
 
-			# Replace encryption key with new value
-			sudo xmlstarlet ed -L -u "/yazgfs/config/encryption_key" -v "$keyvalue" "$configpath"
-			echo -e "${GREEN}The encryption key has been updated.${NC}"
-			;;
-		[nN][oO]|[nN])
-			echo -e "${GREEN}No changes have been made.${NC}"
-			;;
-		*)
-			echo -e "${RED}Invalid response.${NC}"
-			;;
-		esac
-	fi
-	echo -e "#################################################################\n"
-	echo -e "If you encountered problems, you can find the timestamped backup config file here: ${GREEN}$config_backup${NC}.\n"
+else
+echo -e "${YELLOW}Encryption key exists.${NC}"
+read -rp "Do you want to update it? (yes/no): " response
+case $response in
+[yY][eE][sS]|[yY])
+echo -e "${YELLOW}Updating encryption key...${NC}"
+sleep 1s
+
+  # Generate encryption key and set to variable
+  keyvalue=$(pwgen 32 -1)
+
+  # Backup the original config file
+  local config_backup="/tmp/$val.koha-conf.xml.bkp-$(date +%d-%m-%Y-%Hh%Mm%Ss)"
+  sudo cp "$configpath" "$config_backup"
+
+  # Replace encryption key with new value
+  sudo xmlstarlet ed -L -u "/yazgfs/config/encryption_key" -v "$keyvalue" "$configpath"
+  echo -e "${GREEN}The encryption key has been updated.${NC}"
+
+  # Prompt to restore original config
+  read -rp "Do you want to restore the original file? (yes/no): " response
+case $response in
+[yY][eE][sS]|[yY])
+sudo cp "$config_backup" "$configpath"
+echo -e "${GREEN}The original config has been restored.${NC}"
+;;
+[nN][oO]|[nN])
+echo -e "${GREEN}Changes kept.${NC}"
+;;
+*)
+echo -e "${RED}Invalid response.${NC}"
+;;
+esac
+;;
+[nN][oO]|[nN])
+echo -e "${GREEN}No changes have been made.${NC}"
+;;
+*)
+echo -e "${RED}Invalid response.${NC}"
+;;
+esac
+fi
+echo -e "#################################################################\n"
+echo -e "If you encountered problems, you can find the timestamped backup config file here: ${GREEN}$config_backup${NC}.\n"
 done
