config options, use sed to strip leading text

diff --git a/koha-capache b/koha-capache
--- a/koha-capache
+++ b/koha-capache
@@ -1,50 +1,124 @@
 #!/bin/bash
+# ------------------------------------------------------------------
+# Author: Lennon Mazonde
+# GitHub: @grandmaestr
+# Title: koha-capache
+# Description: 
+# 	This script configures the OPAC and Staff URL in the 
+# 	Apache conf (/etc/apache2/sites-enabled/) file for your Koha instance
+# 	You will need to configure Apache config files (/etc/apache2/sites-enabled/)
+# 	You can copy and paste this script onto your server and make it executable by running "chmod a+x /path/to/file_name"
+# 	To run the script, simply go to "/path/to/file_name" or if it's in your home directory, run "~/file_name" in the CLI.
+# 	This script is interactive, so you'll be prompted for input at various stages.
+# 	You can modify or use this script however you like but I'd really appreciate it if you give me a shout out or attribution if you post it elsewhere :)
 
-# This script installs koha-common and  dependencies on a bare-bones Ubuntu server.
-# I've tested this on Ubuntu Server 20.04LTS but it should work on other Debian distros. 
-# You will need to configure Apache config files (/etc/apache2/sites-enabled/)
-# You can copy and paste this script onto your server and make it executable by running "chmod a+x /path/to/file_name"
-# To run the script, simply go to "/path/to/file_name" or if it's in your home directory, run "~/file_name" in the CLI.
-# This script is interactive, so you'll be prompted for input at various stages.
-# You can modify or use this script however you like but I'd really appreciate it if you give me a shout out or attribution if you post it elsewhere :)
+# ------------------------------------------------------------------
 
-# Prompt the user for the name of your koha instance. Input something simple and easily distinguishable from other instances.
-echo "You have the following Koha instances running on this server:"
-echo $(koha-list)
+# Script version
+VERSION=0.1.0
+# Set the name of the script to variable
+SCRIPT_NAME="$(basename ${0})"
 
-printf "\n"
+# ------Help--------------------------------------------------------
+Help(){
+    # Display Help
+    cat <<EOF
+        Usage: $SCRIPT_NAME -ihv args
 
-read -p "Enter the name of each  Koha instance you want to configure separated by a space: " -a kinstance
+        Options:
+        i - instanceid. The name of the koha instance. One instance id per option.
+        h - help. Print this help.
+        v - version. Print the script version.
 
-opac=""
-staff=""
+        Example:
+        To activate a single instance called "library", run:
+            $SCRIPT_NAME -i library
+        To activate multiple instances, run
+                $SCRIPT_NAME -i library1 -i library2 ...
+EOF
+}
+# --- Options processing -------------------------------------------
+if [ $# == 0 ] ; then
+    Help
+    exit 1;
+fi
 
-for instancename in "${kinstance[@]}"; do
+while getopts ":i:vh" optname; do
+    case "$optname" in
+      v)
+        echo "Version $VERSION"
+        exit 0;
+        ;;
+      i)  
+        instanceid+=("$OPTARG")
+        ;;
+      h)
+        Help
+        exit 0;
+        ;;
+      \?)
+        echo "Unknown option $OPTARG"
+        Help
+        exit 0;
+        ;;
+      :)
+        echo "Error: you must provide at least one instance name for option -$OPTARG"
+        exit 0;
+        ;;
+      *)
+        echo "Unknown error while processing options"
+        Help
+        exit 0;
+        ;;
+    esac
+  done
+
+shift $(($OPTIND - 1))
+
+param1=$1
+param2=$2
+
+# --- Locks -------------------------------------------------------
+LOCK_FILE=/tmp/$SUBJECT.lock
+if [ -f "$LOCK_FILE" ]; then
+   echo "Script is already running"
+   exit
+fi
+
+trap "rm -f $LOCK_FILE" EXIT
+touch $LOCK_FILE
+
+# --- Body --------------------------------------------------------
+
+for val in "${instanceid[@]}"; do
+	opac=""
+	staff=""
+
 	while
-	read -p "Continue configuring $instancename.conf (y/n)" response && [[ $response =~ ^([yY][eE][sS]|[yY])$ ]] 
+		read -p "Update $val.conf? (y/n): " response && [[ $response =~ ^([yY][eE][sS]|[yY])$ ]] 
 	do
+		# Prompt user to enter their Staff URL
+		read -p "New Staff/admin page url $val (Leave out http:// or https://) : " staffdomain
+		
+		# Prompt user to enter their OPAC domain/subdomain
+		read -p "New OPAC url for $val (Leave out http:// or https://) : " opacdomain
+		
+		# Strip out leading http(s):// and set to variable
+		staffurl=$(echo "$staffdomain" | sed "s|.*://||; s|/.*||" )
+		staff+=" ${staffurl}"
+		
+		# Strip out leading http(s):// and set to variable
+		opacurl=$(echo "$opacdomain" | sed "s|.*://||; s|/.*||" )
+		opac+=" ${opacurl}"
 
-		echo "Configuring $instancename.conf"
+		# Replace ServerName with  Staff url 
+		sudo sed  -i "/ServerName*/c\   ServerName $staffurl" /etc/apache2/sites-enabled/$val.conf
 
-		printf ".......... \n"
+		# Replace *ServerName with  OPAC url 
+		sudo sed -i  "0,/ServerName $staffurl/s//ServerName $opacurl/" /etc/apache2/sites-enabled/$val.conf
 
-			# Prompt user to enter their Staff URL
-			read -p "Enter the your Staff url $instancename (Skip http:// or https://):" staffurl
-
-			staff+=" ${staffurl}"
-
-			# Replace ServerName with  OPAC url above
-	                sudo sed  -i "/ServerName*/c\   ServerName $staffurl" /etc/apache2/sites-enabled/$instancename.conf
-
-			# Prompt user to enter their OPAC domain/subdomain
-			read -p "Enter the your OPAC url for $instancename (Skip http:// or https://):" opacurl
-
-			opac+=" ${opacurl}"
-
-			# Replace *ServerName with  OPAC url above
-			sudo sed -i  "0,/ServerName $staffurl/s//ServerName $opacurl/" /etc/apache2/sites-enabled/$instancename.conf
-
-			sudo less /etc/apache2/sites-enabled/$instancename.conf
+		# Print new conf file
+		sudo less /etc/apache2/sites-enabled/$val.conf
 	done
 
 done
